### ISSUE TITLE
Custom page with login short code doesn't appear to allow logins

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/Wild-Apricot-Press#134]
Create a custom page
Insert the short code [wawp_custom_login_form] in block editor/classic editor (doesn't appear to matter either case)
Attempt to login with valid and invalid credentials 

Currently the page just loops and doesn't show invalid login error or logs in successfully

**Comment by asirota** [comment]
@Crednib can you add any details here on your understanding on what happens with a custom page with the login short code.

1. Does it login ok with the correct credentials?
2. Do custom fields get sync'd ok?
3. Does it show a message with invalid credentials if the username/password is incorrect?

What specifically isn't working and we will try to replicate?

**Comment by Crednib** [comment]
Hi Alex,

In regards to my testing with startuphaven.com
1.  Using the wawp-wild-apricot-login page my credentials appear to be
correct (since there is no login button there is no visual information to
confirm other than the page no longer loops (goes back to the login but
returns me to the home page).
2. I can confirm that when working with the Startup Haven team they were
able to confirm that once the login page was working that a WordPress user
profile was generated.  I cannot confirm if 'custom' fields were added.
3. When trying to login with false user/password information I was given
the message "WildApricot has encountered an error and could not complete
your request." This would be my anticipated response for this scenario.

After successfully logging in - but then trying to access the page
'dashboard-2' (which should be accessible for my membership level) I
received the message "Please note that while you are logged into WordPress,
you have not synced your account with WildApricot. Please Log In
<https://startuphaven.com/index.php?pagename=wawp-wild-apricot-login&redirectId=16175>
into
your WildApricot account to sync your data to your WordPress site." My
question would be what (or where) does it trigger that message?  For
further testing, if I was to try and access 'dashboard-3' it should not be
possible.

Hope that is of some help -

Carol Binder, CRM/Database Migration/Formstack/QuickBooks for WildApricot
Follow us on  <https://www.facebook.com/newpathconsulting/> and
<https://www.instagram.com/newpathconsultingteam/>

**Comment by Crednib** [comment]
![image](https://user-images.githubusercontent.com/75815231/229241225-5b057ea7-01c4-46be-b16e-3db311e5784b.png) (from Slack WAP channel)

**Comment by asirota** [comment]
I believe we are seeing this issue across multiple accounts. Here is what I have been able to ascertain:

1. The WildApricot user is successfully logging in.
2. But there are a few pieces of information that appear not to be sync'd:
- Account ID (aka UserID)
- Groups

3. As a result if the Groups are missing than the access control features won't work since the user profile doesn't even have the correct data. I also note several other fields are not being sync'd like Member and Member Since fields

Here's an example:

![image](https://user-images.githubusercontent.com/458134/230111544-29e09e80-1034-4092-969d-4bcf0267fbed.png)

**Comment by asirota** [comment]
During the login it appears this error is being thrown in the wapdebug.log

[3/30/2023, 10:19:26 PM] FATAL ERROR | newpath-wildapricot-press | Account ID: 18317 | class-wa-integration.php:1398 WAWP\WA_Integration->create_user_and_redirect() | There was an error in the WildApricot API and the plugin has to be disabled. Please try again.

**Comment by asirota** [comment]
Here's one site you can use to simulate. I will have another one later today...


Sample Site with sync issues

https://aepc.bedrockwp.com/wp-admin/
user: alex
password: UaYh1iyejV^cL6Q#2ph$GiTy

WA sample username and password for a member with a membership Group

Email: ryan@nimbleweb.co

Password: 6&8fSZ##DPMvwWdo

**Comment by asirota** [comment]
Here's another customer with a similar looking problem

https://katva.thedev.ca/wp-admin

login newpath
password !mt71oCl)D3xPsYKngWafB^u


WA test user:
username me+2@dankitchen.ca
password fdgfsfhf9898b0fd92###4FG

**Comment by Crednib** [comment]
I can confirm that for MPG, at least, that the groups are sync'd (after
login a group was added to my WP profile).  Also, both MPG and StartupHaven
have the names of the groups displayed in the access control panel on pages.

Best regards,
Carol Binder, CRM/Database Migration/Formstack/QuickBooks for WildApricot
Follow us on  <https://www.facebook.com/newpathconsulting/> and
<https://www.instagram.com/newpathconsultingteam/>

**Comment by mDisna** [comment]
On my test site, the contact ID is always recorded for both version 1.0.1 and 1.0.2 - which is different from the examples posted above. Groups are are not being recorded on my test site.

Page restrictions for groups are not working since they aren't being recorded, however I can restrict pages by membership level and that is working correctly.

Changing the login page URL from <kbd>wawp-wild-apricot-login</kbd> to <kbd>custom-login-link</kbd> does not cause any problems with logging in.

Creating a brand new page with the shortcode `[wawp_custom_login_form]` - the login does not work, it just reloads page.

**Comment by asirota** [comment]
Here's the sample sandbox site for startuphaven.com which has issues with accessing a page with access control.

https://gostartuphaven.com/ 

Admin username: admin
Password: Password1!

**Comment by mDisna** [comment]
@asirota do we have admin access for the WA account?

Can I disable plugins on the WP site?

Is the page control through membership level or through groups?

**Comment by asirota** [comment]
I can get an admin account for WA for Startup Haven. 

Yes you can disable plugins on the WP site, since this is a sandbox.

On startuphaven currently the pages dashboard 2 and dashboard 3 have access control through membership level.

Here's a test user that logged in through the login page on the WP site:

http://gostartuphaven.com/wp-admin/user-edit.php?user_id=477

**Comment by krisXh** [comment]
Alex, 

I just started getting this error as well when I asked Members to start testing my site (that was working fine for my test user)

"Please note that while you are logged into WordPress, you have not synced your account with WildApricot. Please [Log In](http://xs651412.xsrv.jp/index.php?pagename=WA-login&redirectId=7834) into your WildApricot account to sync your data to your WordPress site."

http://xs651412.xsrv.jp/join/members-only-home/

- Kristen

**Comment by mDisna** [comment]
@krisXh Hi Kristen, yes, please try the 1.0.2 beta release. You can download it here: https://github.com/NewPath-Consulting/Wild-Apricot-Press/releases/tag/1.0.2b2
